-- ════════════════════════════════════════════════════════════════════════════
--  MÓDULO DISTRIBUIÇÃO — Fase 1 (modelo de dados)
--  CD (matriz) atende requisições das filiais. Nasce COMPLETO/FLEXÍVEL:
--  campos modo (transferencia|compra_interna) e origem (portal|sugestao) já
--  previstos, mesmo que a Fase 1 só ligue o caminho "transferência".
--  Reusa a RPC transferir_estoque (já existente) — este SQL só cria a estrutura.
-- ════════════════════════════════════════════════════════════════════════════

-- 1) Marca quais lojas são Centro de Distribuição (o estoque central é o saldo delas)
alter table public.lojas add column if not exists is_cd boolean not null default false;

-- 2) Requisições (a filial pede itens ao CD)
create table if not exists public.requisicoes (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid not null,
  numero        bigint generated by default as identity,   -- nº amigável (REQ-000148)
  loja_id       uuid not null references public.lojas(id), -- filial solicitante
  cd_loja_id    uuid references public.lojas(id),          -- CD que atende (origem da baixa)
  status        text not null default 'enviada',           -- enviada|em_separacao|a_caminho|recebida|cancelada
  origem        text not null default 'portal',            -- portal|sugestao  (eixo 2 do desenho)
  modo          text not null default 'transferencia',     -- transferencia|compra_interna (eixo 1)
  observacao    text,
  solicitante_id uuid,
  valor_total   numeric,                                    -- custo (transferência) OU preço (compra interna)
  created_at    timestamptz not null default now(),
  separado_em   timestamptz,
  enviado_em    timestamptz,
  recebido_em   timestamptz
);

-- 3) Itens da requisição (pedido x atendido)
create table if not exists public.requisicao_itens (
  id            uuid primary key default gen_random_uuid(),
  requisicao_id uuid not null references public.requisicoes(id) on delete cascade,
  tenant_id     uuid not null,
  insumo_id     uuid not null references public.insumos(id),
  qtd_pedida    numeric not null,
  qtd_atendida  numeric,                                    -- o que o CD realmente separou/enviou
  unidade       text,
  custo_unitario numeric,                                   -- snapshot p/ valorizar a carga
  created_at    timestamptz not null default now()
);

-- 4) Índices
create index if not exists ix_req_tenant_status on public.requisicoes (tenant_id, status);
create index if not exists ix_req_tenant_loja   on public.requisicoes (tenant_id, loja_id);
create index if not exists ix_reqitens_req      on public.requisicao_itens (requisicao_id);

-- 5) RLS por tenant (padrão do projeto: get_my_tenant_id() em USING + WITH CHECK)
alter table public.requisicoes      enable row level security;
alter table public.requisicao_itens enable row level security;

drop policy if exists tenant_policy on public.requisicoes;
create policy tenant_policy on public.requisicoes
  for all using (tenant_id = get_my_tenant_id()) with check (tenant_id = get_my_tenant_id());

drop policy if exists tenant_policy on public.requisicao_itens;
create policy tenant_policy on public.requisicao_itens
  for all using (tenant_id = get_my_tenant_id()) with check (tenant_id = get_my_tenant_id());

grant select, insert, update, delete on public.requisicoes      to authenticated, anon;
grant select, insert, update, delete on public.requisicao_itens to authenticated, anon;

-- Obs.: o modo de distribuição (transferencia|compra_interna) fica em `parametros`
-- (modulo='distribuicao', chave='modo'). O app assume 'transferencia' quando ausente
-- — não precisa pré-gravar nada aqui. A tela de Configurações grava quando o cliente trocar.
